### ISSUE TITLE
pipework_cmd should be sorted

### ISSUE THREAD

**Issue by deitch** [dreamcat4/docker-images#10]
If I have multiple pipework commands, and there is any order required, I have no control over it.

Recommend changing https://github.com/dreamcat4/docker-images/blob/master/pipework/entrypoint.sh#L348 to

```
    _pipework_cmds="$(env | grep -o -e '[^=]*pipework_cmd[^=]*' | sort -n )"
```

This allows me to do things like

``` yml
    00_pipework_cmd_public=eth0 @CONTAINER_ID@ dhclient
    01_pipework_cmd_public=eth0 -i eth2 @CONTAINER_ID@ 192.168.10.10/24@192.18.10.1
```

**Comment by deitch** [comment]
Well, that will not work. You cannot start an environment var with a non-alphabetical character. Still, sorting helps, as I can do

``` yml
    A_pipework_cmd=...
    B_pipework_cmd=...   
```

**Comment by dreamcat4** [comment]
Ok. Thanks for bringing this up. I will update it very soon with your improvement.

BTW it should sort in other ways a number. For example:

``` sh
c01_pipework_cmd=
c02_pipework_cmd=

# or
pipework_cmd_01=
pipework_cmd_02=
```

**Comment by deitch** [comment]
Pleasure. I love this method of using pipework, but not on the host directly. Works great with things like Rancher or other orchestration tools.

Yeah, `c01_pipework_cmd` would work, but then it would sort strangely, with `c100_` before `c20`. `sort -n` solves it, but only if the first character is an integer, which environments do not allow.

Not too worried. What are the chanced someone has 100+ commands? 

In any case, probably worth just doing `sort` and not `sort -n` since it doesn't help and could confuse people.

**Comment by dreamcat4** [comment]
> In any case, probably worth just doing sort and not sort -n since it doesn't help and could confuse people.

OK. Agreed.

**Comment by deitch** [comment]
Looks great, thanks. May I suggest you change the documentation, so people know the commands will be processed in order?

**Comment by dreamcat4** [comment]
Yes. I will alter very slightly the documentation.
