### ISSUE TITLE
Not working on Centos 6.5 and Docker 1.7.1

### ISSUE THREAD

**Issue by tlvu** [dreamcat4/docker-images#13]
docker --version
Docker version 1.7.1, build 786b29d/1.7.1

docker run -v /var/run/docker.sock:/docker.sock --privileged=true --pid=host --net=host  dreamcat4/pipework --help
mkdir: cannot create directory '/sys/fs/cgroup': No such file or directory
mount: mount point /sys/fs/cgroup does not exist
Could not make a tmpfs mount. Did you use -privileged?

uname -a
Linux lvu.mtl.intelerad.com 2.6.32-504.23.4.el6.x86_64 #1 SMP Tue Jun 9 20:57:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dreamcat4** [comment]
I am Ubuntu user - not tested on Centos.

Perhaps check the location of your `docker.sock` on the host filesystem?

**Comment by dreamcat4** [comment]
Pls Google the error msg. And check if different location for `/sys/fs/cgroup`
