### ISSUE TITLE
tvh:master sundtek dvb

### ISSUE THREAD

**Issue by firsttris** [dreamcat4/docker-images#15]
Hello,

is it possible to add sundtek dvb driver to your tvheaded docker-image?

http://wiki.sundtek.de/index.php/TreiberInstallation

regards
tristan

**Comment by dreamcat4** [comment]
Hello @firsttris!

I am very happy to add / improve the compiler flags which build the tvheadend binary to include support for additional optional devices and services. eg hdhomerun etc. So if you are asking for some CC flag i've been missing when compiling tvheadend itself - then yes I will oblige.

However if it's some software which is seperate pkg than tvh. Its better for me to keep this one clean, and for you to fork / `FROM` and make your own tweaked versions derived of my image.

But if it's a DVB input device (some regular tv adapter) appearing in `/dev/*` folder than maybe you should be installing the missing driver on your host environment instead? i.e. not within the container.

Sorry I don't know specifically the device you are talking about. But the link you gave me suggests it might be the 3rd situation. I.e. once your device is working on host side, you can then see it in `/dev/` folder and pass in some flags like `--device=/dev/XYZ`. So it should not be necessary or any benefit to be adding extra softwares inside of the docker tvheadend image.

Or if you want to experiment a bit. Then another way is to run the software `minisatip` to make the connection forward over ethernet as a SATIP server. And tvheadend can act as SATIP client for it's tv input, accepting network connection from your mini SATIP server. That again also requires the DVB device to first be appearing in `/dev/` folder. Which can be on same machine too if you want to try an alternative to the default mechanism of `--device=` docker run flags.

Once you have installed linux drivers, you can test your tv adaptor with the program `w_scan`. And similar linux commandline tools. That is always a recommended first steps on linux before getting involved with trying to make work inside of tvheadend. Many thanks.

**Comment by firsttris** [comment]
Hello @dreamcat4 

thanks for your awnser.

So your saying i do not have to install drivers inside the container just pass the --device ?? correct?

i have 4 DVB devices:

2x DVBSKY S952 DVB-S2
2x Sundtek SKYTV Ultimate 3 DVB-S2

All driver installed on Host

host:
root@tvserv:~# ls /dev/dvb/adapter*
/dev/dvb/adapter0:
demux0  dvr0  frontend0  net0
/dev/dvb/adapter1:
demux0  dvr0  frontend0  net0
/dev/dvb/adapter2:
demux0  dvr0  frontend0
/dev/dvb/adapter3:
demux0  dvr0  frontend0

tvheadend on host:
https://dl.dropboxusercontent.com/u/13344648/dvbDevicesOnHost.PNG

Starting your tvh:master image (unchanged) with these device parameters:
--device=/dev/dvb/adapter0/demux0:/dev/dvb/adapter0/demux0 
--device=/dev/dvb/adapter0/dvr0:/dev/dvb/adapter0/dvr0 
--device=/dev/dvb/adapter0/frontend0:/dev/dvb/adapter0/frontend0 
--device=/dev/dvb/adapter0/net0:/dev/dvb/adapter0/net0
--device=/dev/dvb/adapter1/demux0:/dev/dvb/adapter1/demux0 
--device=/dev/dvb/adapter1/dvr0:/dev/dvb/adapter1/dvr0 
--device=/dev/dvb/adapter1/frontend0:/dev/dvb/adapter1/frontend0 
--device=/dev/dvb/adapter1/net0:/dev/dvb/adapter1/net0
--device=/dev/dvb/adapter2/demux0:/dev/dvb/adapter2/demux0 
--device=/dev/dvb/adapter2/dvr0:/dev/dvb/adapter2/dvr0 
--device=/dev/dvb/adapter2/frontend0:/dev/dvb/adapter2/frontend0 
--device=/dev/dvb/adapter3/demux0:/dev/dvb/adapter3/demux0 
--device=/dev/dvb/adapter3/dvr0:/dev/dvb/adapter3/dvr0 
--device=/dev/dvb/adapter3/frontend0:/dev/dvb/adapter3/frontend0 

check dvb devices with shell inside the container:
root@tvserv:~# docker exec -it f47bf699c6744c2cd8a28d2e6dbb56767b9650284c29246d640fe4e687a2c31d /bin/bash
root@tvserv:/# ls /dev/dvb/adapter*
/dev/dvb/adapter0:
demux0  dvr0  frontend0  net0

/dev/dvb/adapter1:
demux0  dvr0  frontend0  net0

/dev/dvb/adapter2:
demux0  dvr0  frontend0

/dev/dvb/adapter3:
demux0  dvr0  frontend0

dvb devices in tvheadend (Container):
https://dl.dropboxusercontent.com/u/13344648/dvb-devices-container.PNG

only DVBSKY is shown in tvheadend any idea whats might by the problem?

Permissions of dvb-devices (same as host) in Container:

root@tvserv:/# ls -l /dev/dvb/adapter*
/dev/dvb/adapter0:
total 0
crw-rw---- 1 root video 212, 1 Jan 11 12:58 demux0
crw-rw---- 1 root video 212, 2 Jan 11 12:58 dvr0
crw-rw---- 1 root video 212, 0 Jan 11 12:58 frontend0
crw-rw---- 1 root video 212, 3 Jan 11 12:58 net0

/dev/dvb/adapter1:
total 0
crw-rw---- 1 root video 212, 5 Jan 11 12:58 demux0
crw-rw---- 1 root video 212, 6 Jan 11 12:58 dvr0
crw-rw---- 1 root video 212, 4 Jan 11 12:58 frontend0
crw-rw---- 1 root video 212, 7 Jan 11 12:58 net0

/dev/dvb/adapter2:
total 0
crwxrwxrwx 1 root root 212,  9 Jan 11 12:58 demux0
crwxrwxrwx 1 root root 212, 10 Jan 11 12:58 dvr0
crwxrwxrwx 1 root root 212,  8 Jan 11 12:58 frontend0

/dev/dvb/adapter3:
total 0
crwxrwxrwx 1 root root 212, 12 Jan 11 12:58 demux0
crwxrwxrwx 1 root root 212, 13 Jan 11 12:58 dvr0
crwxrwxrwx 1 root root 212, 11 Jan 11 12:58 frontend0

regards
firsttris

**Comment by dreamcat4** [comment]
OK @firsttris,
That is correct method. But if you have a newer version of Docker, you may instead simply use wildcard to `--device` to specify all your `/dev/dvb/*` devices. Just try it.

As for understanding why tvheadend does not recognise. Well you need to pay more attention to my last most comment:

> Once you have installed linux drivers, you can test your tv adaptor with the program w_scan. And similar linux commandline tools. That is always a recommended first steps on linux before getting involved with trying to make work inside of tvheadend.

It can be for many reasons. For example I myself also had problems with a specific piece of hardware... and turned out it was broken device / would not work. So please check around on the net, and you will find some tutorials / guides how to use `w_scan` and similar linux commands to test your DVB devices first of all.

Than once you are sure it's all fully working can go back to finish up in tvheadend.
Many thanks.

**Comment by firsttris** [comment]
I managed it.
But currently you need to add something to the image to make sundtek tuner work, i think it only makes sense in a fork.

Thx for your help

**Comment by alex-sainer** [comment]
@firsttris can you please explain what you have done to get the sundtek tuner working? 

regards, 
Alex

**Comment by firsttris** [comment]
you need to remove sundtek driver from host and install in the guest.
(currently the only way - talked to sundtek support)

i forked the dockerfile to do this:

https://github.com/firsttris/docker-images/blob/master/tvh/master/Dockerfile

regards
tristan

**Comment by jteeuw** [comment]
Hi firsttris , 

did suntek give a reason why it must be installed in the guest , ( i am trying to use it with unraid )

**Comment by firsttris** [comment]
Hi,

i think their driver is using a different way to communicate to the device then usual dvb-cards.

sundtek said docker integration for their driver may be implemented in the future.

You might contact Sundtek support via skype "sundtek"

or

http://chat.sundtek.de

please let me know if there a new way to use the sundtek driver with docker.

regards
firsttris

**Comment by MarvAmBass** [comment]
@firsttris does your container work with a sundtek without installing drivers on host?

**Comment by firsttris** [comment]
yes, it will be installed in the container. when you install it on the host it will not work with my version.
i have an updated version which i will push to git.

**Comment by MarvAmBass** [comment]
thanks

**Comment by firsttris** [comment]
here is my image
https://github.com/firsttris/tvheadend-sundtek-docker
i put some infos together
