### ISSUE TITLE
error: can't connect to unix:///docker.sock

### ISSUE THREAD

**Issue by ikedaj** [dreamcat4/docker-images#17]
I'm trying to run the latest dreamcat4/pipework with docker v1.8.2/CentOS7,
and facing the error, "error: can't connect to unix:///docker.sock"
Need to set some options for docker daemon?

```
# docker -v
Docker version 1.8.2-el7.centos, build a01dc02/1.8.2

# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)

# docker images | grep dreamcat4
docker.io/dreamcat4/pipework     latest              8a25bbdbf03c        10 days ago         251.9 MB
docker.io/dreamcat4/pipework     1.0.6               58d0fbb45a32        10 months ago       186.5 MB
```

```
# docker run \
   --restart=always \
   --name=pipework \
   -v /var/run/docker.sock:/docker.sock \
   --privileged=true \
  --pid=host \
   --net=host \
   -e run_mode=batch,daemon \
   -e host_route=true \
   dreamcat4/pipework --help
Error response from daemon: client is newer than server (client API version: 1.21, server API version: 1.20)
error: can't connect to unix:///docker.sock
```

```
# ls -l /var/run/docker.sock
srw-rw---- 1 root root 0  2月 15 19:11 /var/run/docker.sock
```

v1.0.6 works well.

```
# docker run \
   --restart=always \
   --name=pipework \
   -v /var/run/docker.sock:/docker.sock \
   --privileged=true \
   --pid=host \
   --net=host \
   -e run_mode=batch,daemon \
   -e host_route=true \
   -d dreamcat4/pipework:1.0.6
```

```
# docker run \
   --name=sample \
   --net=none \
   -e 'pipework_cmd_eth0=br0 -i eth0 @CONTAINER_NAME@ 172.26.210.212/24' \
   -e 'pipework_cmd_eth1=br1 -i eth1 @CONTAINER_NAME@ 192.168.100.112/24' \
   -itd busybox
```

```
# docker exec sample ip address show | grep "inet "
    inet 127.0.0.1/8 scope host lo
    inet 172.26.210.212/24 scope global eth0
    inet 192.168.100.112/24 scope global eth1
```

**Comment by dreamcat4** [comment]
Looks like docker version mismatch:

``` sh
Error response from daemon: client is newer than server (client API version: 1.21, server API version: 1.20)
error: can't connect to unix:///docker.sock
```

As described here: https://docs.docker.com/engine/reference/api/docker_remote_api/

1.9.x   1.21
1.8.x   1.20

Uhm...

1) It would be best solution to upgrade your host's docker version.

But if your host's distro is still on 1.8.x, then 1.9.x may not be available as an official RPM just yet. Until then you could do something else like:

2) Use a slightly earlier version of pipework container (like try subtracting -0.1, or -0.2 from the latest version number).

3) Perhaps there is an override to force compatibility between API versions?

Ah-ha!

4) My container does not mount the `docker` binary program into the container from host side. But that is what is causing this API version mismatch. SO maybe it would be simplest to just force mount the older host `docker` minary file over the container's newer version of `docker` program. That should be easy (same way as the `docker.sock`).

Sorry I didn't include instructions to do that ^^ but would be happy to add them to FAQ / troubleshooting section if it works.

5) Else can rebuild my pipework Dockerfile yourself with a different version of `docker` to match your host's. The pipework image uses `ubuntu-16.04` base image now.

I am thinking the best / simplest solution is probably number 4). What do you think?

**Comment by dreamcat4** [comment]
For 4) you just need to add extra argument to your `pipework:latest`'s docker run flags:

``` sh
docker run ... blah ... -v /PATH_TO_HOST/docker:/usr/bin/docker dreamcat4/pipework:latest ... blah ...
```

And it should work again.

**Comment by ikedaj** [comment]
I added "-v /bin/docker:/usr/bin/docker" to docker run;

```
# docker run \
--restart=always \
--name=pipework \
-v /var/run/docker.sock:/docker.sock \
-v /bin/docker:/usr/bin/docker \
--privileged=true \
--pid=host \
--net=host \
-e run_mode=batch,daemon \
-e host_route=true \
-d dreamcat4/pipework:latest
```

It seems that there is still version mismatch...

```
# docker logs -f pipework
docker: error while loading shared libraries: libdevmapper.so.1.02: cannot open shared object file: No such file or directory
error: can't connect to unix:///docker.sock
```

**Comment by ikedaj** [comment]
Add also "-v /usr/lib64/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02";

```
# docker run \
--restart=always \
--name=pipework \
-v /var/run/docker.sock:/docker.sock \
-v /bin/docker:/usr/bin/docker \
-v /usr/lib64/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02 \
--privileged=true \
--pid=host \
--net=host \
-e run_mode=batch,daemon \
-e host_route=true \
-d dreamcat4/pipework:latest
```

Works fine?

```
# docker run \
--name=sample \
--net=none \
-e 'pipework_cmd_eth0=br0 -i eth0 @CONTAINER_NAME@ 172.26.210.212/24' \
-e 'pipework_cmd_eth1=br1 -i eth1 @CONTAINER_NAME@ 192.168.100.112/24' \
-itd busybox
```

```
# docker exec sample ip address show | grep "inet "
    inet 127.0.0.1/8 scope host lo
    inet 172.26.210.212/24 scope global eth0
    inet 192.168.100.112/24 scope global eth1
```

**Comment by ikedaj** [comment]
I will select (2) for now, dreamcat4/pipework:1.1.3 runs docker v1.7.1.
Thanks!

```
# docker run \
--restart=always \
--name=pipework \
-v /var/run/docker.sock:/docker.sock \
--privileged=true \
--pid=host \
--net=host \
-e run_mode=batch,daemon \
-e host_route=true \
-d dreamcat4/pipework:1.1.3
```

```
# docker exec pipework docker -v
Docker version 1.7.1, build 786b29d
```

**Comment by dreamcat4** [comment]
Interesting. In older docker version it used to be that the `docker` program was just a single file. So possible to mount into container without other worries. Perhaps that's no longer the case now it's got more complex.

Sorry it is difficult to fully support all / many distros with different docker versions simultaneously. Because they update their pkgs on different schedules.

I'm glad you found a solution for time being. Until the Centos rpms get updated.

**Comment by ikedaj** [comment]
I found the following PR,
"Add a DOCKER_API_VERSION env var"
https://github.com/docker/docker/pull/15964

If dreamcat4/pipework supports docker v1.10,
"-e  DOCKER_API_VERSION=1.20" would be help.

**Comment by dreamcat4** [comment]
@ikedaj reading that PR you last linked, it also sounds like could mound a `~/.docker` config file in the client (e.g. `docker run -v HOSTFILE:/root/.docker`. To contain same instruction to use older API version. Not sure it that is any better, its probably just the same string `DOCKER_API_VERSION=1.20` to put in the config file.

It's probably just easier to use `-e` flag to set the ENV variable like you show above ^^. Perhaps another time you will try it and report back. Whenever / at your convenience.

**Comment by ikedaj** [comment]
I just tried, difficult to handle more than expected...
I will try again if a good idea comes to me :)

```
# cd /tmp
# wget https://get.docker.com/builds/Linux/x86_64/docker-1.10.1
# chmod +x docker-1.10.1
```

```
# docker run \
--restart=always \
--name=pipework \
-v /var/run/docker.sock:/docker.sock \
-v /tmp/docker-1.10.1:/usr/bin/docker \
-e DOCKER_API_VERSION=1.20 \
--privileged=true \
--pid=host \
--net=host \
-e run_mode=batch,daemon \
-e host_route=true \
-d dreamcat4/pipework:latest
```

```
# docker logs -f pipework

WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
WARNING: No cpu shares support
WARNING: No cpuset support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted
cat: /var/run/tail_f.NAn.pid: No such file or directory
Error response from daemon: json: cannot unmarshal object into Go value of type []string
/entrypoint.sh: line 34: kill: (32528) - No such process
```

**Comment by dreamcat4** [comment]
OK sorry I didn't mean to waste your time to be trying things that isn't working. In particular this line:

``` sh
Error response from daemon: json: cannot unmarshal object into Go value of type
```

Sounds like they are still not compatible. Perhaps setting that flag doesn't "genuinely" change the API command set being sent/receive. If it only changes the API identificatiion string being send during connection handsahke. Then that's risky / prone to unknown errors we don't want.

Well I don't know that for certain the meaning of the flag. The docker people should be able to say for sure.

So ATM I think we should just recommend to any other affected people: just do what you said for 2):

> I will select (2) for now, dreamcat4/pipework:1.1.3 runs docker v1.7.1.

Which is a very good advice. Many thanks for discovering it.

**Comment by ikedaj** [comment]
Thank you for the detailed explanations.
tag1.1.3 works well, no problem so far.
