### ISSUE TITLE
how can I add two network card ?

### ISSUE THREAD

**Issue by larrycai** [dreamcat4/docker-images#18]
Here is the command I use in docker-compose

```
    - pipework_cmd_that_creates_private_bridge= br1 -i eth0 @CONTAINER_NAME@ 192.168.0.1
    - pipework_cmd_that_creates_private_bridge= br2 -i eth1 @CONTAINER_NAME@ 192.168.1.1
```

It seems only the latest command takes affect ? how can I add two bridge ?

**Comment by dreamcat4** [comment]
Hi,
You have put the same variable twice. You just need to name the 2 variables differently to each other.

``` yaml
    - pipework_cmd_1= br1 -i eth0 @CONTAINER_NAME@ 192.168.0.1
    - pipework_cmd_2= br2 -i eth1 @CONTAINER_NAME@ 192.168.1.1
```

BTW, new docker networking features in v1.10:

http://stackoverflow.com/questions/35742807/docker-1-10-containers-ip-in-lan
