### ISSUE TITLE
crashing smbd with docker 1.11.1

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [dreamcat4/docker-images#22]
Hi there,

the end of samba docker log shows:

```
nmbd version 4.3.8-Ubuntu started.
Copyright Andrew Tridgell and the Samba Team 1992-2015
STATUS=daemon 'nmbd' finished starting up and ready to serve connections
EOF on stdin
Got SIGTERM: going down...
/usr/bin/samba.sh exited 0
```

Is maybe this fix related?
https://github.com/dperson/samba/commit/bec23147166f5e28fc129623f26e5ba1337fdd8c

**Comment by dreamcat4** [comment]
Hi there. Thanks for letting me know. It certainly helps to stay on top of these things. Indeed its same issue, apologies for not fixing it sooner. Have applied your PR now.

**Comment by cguentherTUChemnitz** [comment]
The fix does not seem to be propagated to the dockerhub images. Neither the sable nor the latest images contains the fix. Please rebuild and update those images.

**Comment by dreamcat4** [comment]
Yep. They are scheduled (by cron initiated webook) to rebuild every evening.

But its manually triggered now if you cannot wait for that. It is in the build queue.

**Comment by cguentherTUChemnitz** [comment]
thanks
