### ISSUE TITLE
Please use Python 3 instead of Python 2 for Limnoria.

### ISSUE THREAD

**Issue by progval** [dreamcat4/docker-images#24]
Limnoria supports Python 3 better than Python 2 for awhile now; and Python 2 support may be dropped in the future.

**Comment by dreamcat4** [comment]
Ah yes hi there. Thanks for the heads up @ProgVal. It is most welcome

It is a signicant enough change to require re-testing. Unfortunately I am just too busy at the moment with other un-related things. But shall definately keep this issue open, to be doing it the next time around. Whenever will come back / or have some reason to work on it again.

Many thanks.

**Comment by dreamcat4** [comment]
Done, it is updated to python3 and 20.04 now.

**Comment by progval** [comment]
thanks!
