### ISSUE TITLE
[samba] The permission of created file via samba is 744.

### ISSUE THREAD

**Issue by ermaker** [dreamcat4/docker-images#25]
Hello, I have a question.

I created a file via samba and I checked the permission of it. The permission is 744.
But I want to set the permission of the file to non-executable.

So I checked the configuration file:

```
[global]
...
   directory mask = 0775
   force create mode = 0664
   force directory mode = 0775
```

I think global setting is that executable permission will be not set for normal files to create, but it does not work.

**Comment by dreamcat4** [comment]
Sorry I'm not sure how to do it. Please submit a patch or PR if you can.

**Comment by ermaker** [comment]
Thank you for quick reply. I will submit PR if I fix it.
