### ISSUE TITLE
What FROM?

### ISSUE THREAD

**Issue by sja** [dreamcat4/docker-images#26]
In your [README](https://github.com/dreamcat4/docker-images/blob/master/tvh/README.md) you advise to use `ubuntu-debootstrap:14.04` as base, here in the example you're using another image. What is the correct one?

**Comment by dreamcat4** [comment]
Hi sorry that is deprecated / old text. The best base image now is simply `ubuntu:16.04`. The latest official ubuntu image.

**Comment by sja** [comment]
Ok, thanks.

**Comment by dreamcat4** [comment]
I will keep this issue open, until I update / fix the documentation comments about it. Many thanks for bringing it to my attention here.

**Comment by gh0st** [comment]
I _think_ you've updated that documentation.
