### ISSUE TITLE
Pipework support for Docker 1.10 and above

### ISSUE THREAD

**Issue by tinglis1** [dreamcat4/docker-images#27]
I realise that there are new networking features in the Docker 1.10 but these do no do what I need for my system. Hopefully they will in the future.
This container work on startup but not on live events in Docker 1.10 but there has been a change in the order of the information on the event_line.

The old line looked like
`2015-06-10T16:38:12.000000000Z 753ce24472db2af099328ad161f1af70da0f4bc9fa00af2a4e82625f56eb67f2: (from dreamcat4/tvheadend:latest) start`

The new line looks like:
`2016-08-30T15:22:50.222511284+09:30 container start 49c7aa4ef512bf488821d6118ecf4d101461db1a3d7f7346a5cee2200ad1bb56 '(image=dreamcat4/pipework,' 'name=pipework)`

I have isolated the issue to lines 444 and 445.
They currently read:
`container_id="$(echo -e "$event_line_sanitized" | cut -d ' ' -f3)"`
`event="$(echo -e "$event_line_sanitized" | cut -d ' ' -f6)"`

For Docker 1.10 need to be:
`container_id="$(echo -e "$event_line_sanitized" | cut -d ' ' -f5)"`
`event="$(echo -e "$event_line_sanitized" | cut -d ' ' -f5)"`

One fix would probably read the docker version and apply the correct template based on the version. 
Another would be to tag a new version for 1.10 on docker hub.

**Comment by dreamcat4** [comment]
Thanks for investigating this. Yes I agree the solution you suggest is very appropriate one that you propose. It would be best if we can do it based on docker version. As some users do seem to be stuck on wanting / needing to keep going with much older versions of docker.

If you can put it into a PR and test that its OK then would very much appreciate that. And be happy to accept such a Pull request. Otherwise sorry I'm a bit busy ATM and you would need to wait a few more days for me to get around to trying it / testing it.

Anyway heres what I've come up with based on your comments:

Do this once near the top of the script, during initialization:

``` sh
_docker_ver_maj_min="$(docker version | grep -e "^ Version:" | grep -m1 -o -e "[0-9\.]*" | cut -d. -f1-2)"
if [ ! "$(echo $_docker_ver_maj_min '>=' 1.10 | bc -l)" = "1" ]; then
    _old_event_lines=true
fi
```

then later on:

``` sh
if [ "$_old_event_lines" ]; then
  container_id="$(echo -e "$event_line_sanitized" | cut -d ' ' -f3)"
  event="$(echo -e "$event_line_sanitized" | cut -d ' ' -f6)"
else
  container_id="$(echo -e "$event_line_sanitized" | cut -d ' ' -f5)"
  event="$(echo -e "$event_line_sanitized" | cut -d ' ' -f5)"
fi
```

Would that work perhaps? Do you have the time to test it? Presumably in the new version of docker. Since have stopped using Pipework now myself. Many thanks.

**Comment by tinglis1** [comment]
After much time scouring the code I finally read the documentation again and found the debug feature. Found the problem a few minutes later.

Looks like you have done the difficult part already. I will hopefully have some time over the few days to test it out.

FYI, I use it with unRAID so I get very little say over what version of Docker I use. I will put it to the unRAID community to test it out after. [unRAID Pipework](https://lime-technology.com/forum/index.php?topic=43970.0)

**Comment by tinglis1** [comment]
I have done some testing and made some modifications. Docker uses semantic versioning so when using math version 1.9 looks higher than 1.10.
I have tested the following code and it is working with docker 1.10. I also forced the version variable down to an older version and got the same problem as before.

I dropped this section in just after the docker socket test.

``` shell
# Get the semantic version and store the major and minor versions
_docker_semver="$(docker version | grep -e "^ Version:" | grep -m1 -o -e "[0-9\.]*")"
_docker_semver_maj="$(echo "$_docker_semver" | cut -d. -f1)"
_docker_semver_min="$(echo "$_docker_semver" | cut -d. -f2)"
if [[ $_docker_semver_maj -le 1 ]] && [[ $_docker_semver_min -lt 10 ]] ; then
    _old_event_lines=true
fi
```

I made a small change to the if statement, it was a mistake I made in my opening post about what sections to return.

``` shell
        if [ "$_old_event_lines" ]; then
          container_id="$(echo -e "$event_line_sanitized" | cut -d ' ' -f3)"
          event="$(echo -e "$event_line_sanitized" | cut -d ' ' -f6)"
        else
          container_id="$(echo -e "$event_line_sanitized" | cut -d ' ' -f5)"
          event="$(echo -e "$event_line_sanitized" | cut -d ' ' -f4)"
        fi
```

I can do the pull request to update the code. I haven't done a pull request before so I'll need to figure that one out.

**Comment by dreamcat4** [comment]
OK looks fine to me, please raise a new PR.
