### ISSUE TITLE
Investigate using --cap-add=NET_ADMIN

### ISSUE THREAD

**Issue by firecat53** [dreamcat4/docker-images#3]
Wondering if NET_ADMIN is sufficient to replace --privileged when running the pipework container.

Thanks!

**Comment by dreamcat4** [comment]
Hi. I'm not going to bother doing this. As the image must already have certain very powerful privelidges. It seems like specifying many seperate `--cap-add` options is not worthwhile... Just makes running the container more hassle / lowers the usability.

However if anyone wants to clue me in as to what is the right combination of `--cap-add` options (for pipework to work well). Then I'll happily add those specific infos into the documentation.

**Comment by dreamcat4** [comment]
FYI - did originally try with just a few of them, including `NET_ADMIN` and such. It didn't work. There's definitely other options required. It's just not known which ones. Feel free to play around with the various combinations in your own time.
