### ISSUE TITLE
pxe docker image - DHCP fails to give an address

### ISSUE THREAD

**Issue by Clement-TS** [dreamcat4/docker-images#31]
Hi!
there is very little documentation on how you run your docker-image to provide a PXE boot to devices :p I found out that you took inspiration from this image: https://github.com/jpetazzo/pxe, therefore I decided to use the same method as `jpetazzo`:

```sh
docker build -t pxe .
PXECID=$(docker run --name pxe --cap-add NET_ADMIN -d pxe)
sudo pipework br0 $PXECID 192.168.242.1/24
sudo vconfig add eth0 72
sudo brctl addif br0 eth0.72
```

Then I start *virtualbox* for testing, starting a new image with PXE boot, and its `eth0` bridged to the host `br0`. It actually do something in the container logs:

```
$ docker logs -f pxe
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
dnsmasq: started, version 2.76 DNS disabled
dnsmasq: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
dnsmasq-dhcp: DHCP, proxy on subnet 172.17.0.2
dnsmasq-tftp: TFTP root is /pxe 
dnsmasq-dhcp: no address range available for DHCP request via eth1
dnsmasq-dhcp: no address range available for DHCP request via eth1
dnsmasq-dhcp: no address range available for DHCP request via eth1
dnsmasq-dhcp: no address range available for DHCP request via eth1
```
But there is an error and it cannot go further. Do you have any clue on this?
Thank you a lot!

**Comment by dreamcat4** [comment]
You can add `set -x` near the top of the file  /etc/services.d/dnsmasq/run to see more of what its doing. The log messages shown here seem to suggest that you havent got the networking setup properly.

As for how to do that with VMs honestly I dont know. Been using the docker macvlan driver on linux, which works well and so no need for pipework anymore. It sets up eth0 on the LAN network.

**Comment by Clement-TS** [comment]
Thank you for the info. I really prefer to use macvlan instead of pipework. I also needed to add a dhcp server (there were no dhcp on my vlan), I had to customize ` /etc/services.d/dnsmasq/run` a little.

About iso files, am I supposed to drop them into the `/pxe` volume? What's the use case?
Thanks again,

**Comment by dreamcat4** [comment]
Well no. But you do need to copy 'certain importanct boot files' *from* the ISOs into

https://github.com/dreamcat4/docker-images/tree/master/pxe/pxe.default/iso/extracted

Otherwise those menu entries will not work.

You should also dounle-check that they are available over HTTP on port 80 of this running container. Which should be taken care of by inhereted nginx in the Dockerfile. Assuming you didnt change that or block it from working somehow.

No, the ISO files need to be made available over SAMBA. Consult boot.ipxe for more information,

https://github.com/dreamcat4/docker-images/blob/master/pxe/pxe.default/ipxe/boot.ipxe
