### ISSUE TITLE
Upgrade to 4.2

### ISSUE THREAD

**Issue by joswart** [dreamcat4/docker-images#35]
It would be really appreciated if you could update the image to 4.2.

According to maximilianwollnik, it should be possible without further issue:

"I have cloned your stable repo, have replaced the line
&& echo deb https://dl.bintray.com/dreamcat4/ubuntu ${tvh_release} main > /etc/apt/sources.list.d/tvheadend.list \

with

&& echo deb https://dl.bintray.com/tvheadend/deb xenial stable-4.2 > /etc/apt/sources.list.d/tvheadend.list \

and rebuilt the image. Everything works perfectly with the latest official release."

**Comment by dreamcat4** [comment]
Done, tvheadend docker images are all updated now. For all of the different branches.
