### ISSUE TITLE
standard_init_linux.go:187: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by deisi** [dreamcat4/docker-images#37]
When I try to run:

```
docker run -v /home/alarm/recordings/:/recordings dreamcat4/tvheadend
```
I get
```
standard_init_linux.go:187: exec user process caused "exec format error"
```

Im trying to run on Raspberry Pi maybe that is the issue?

**Comment by dreamcat4** [comment]
Yes. These docker images are compiled for intel 64-bit only. While the rPi has an ARM cpu in it. They are not compatible.
