### ISSUE TITLE
Pipework: pipework commands not run when container is restarted

### ISSUE THREAD

**Issue by schmurfy** [dreamcat4/docker-images#40]
I have a container with this environment:
```
pipework_cmd: eth0 -i eth1 @CONTAINER_NAME@ a.x.y.z/32
```

This works fine when the container is created but if the container is stopped and started again the ip is no longer associated with it.

**Comment by schmurfy** [comment]
I found more about this when switching debug mode, the problem is that I use a `/32` which ends up running `fping -c1 -t200` and after that the script is stuck.

**Comment by micw** [comment]
Got the same issue, how did you fixed this?

**Comment by schmurfy** [comment]
@micw I never fixed it, the project never got into production so I just gave up on this.
