### ISSUE TITLE
Can't load boot menu 

### ISSUE THREAD

**Issue by diversunt** [dreamcat4/docker-images#50]
Hello!
I trying boot to standard "boot menu" for the test, but "boot menu" give me error is below.
Can you help me fix that? 
![image](https://user-images.githubusercontent.com/38781759/102998030-654d1380-4537-11eb-8c44-9a900621979b.png)
Thanks!

**Comment by oXis** [comment]
I think `menu-timeout` is not defined by default, that's why you have `"": invalid integer value`.
 
Just add `set menu-timeout 30000` to `boot.ipxe`, before the `choose` command. It sets the timeout to 30 seconds.
```
set menu-timeout 30000
choose --timeout ${menu-timeout} --default ${menu-default} selected || goto cancel
set menu-timeout 0
```

**Comment by dreamcat4** [comment]
Thanks! The change is pushed to github. And have queued up a new build on dockerhub
