### ISSUE TITLE
Support for multiple pipework commands?

### ISSUE THREAD

**Issue by deitch** [dreamcat4/docker-images#8]
Is there support for multiple pipework commands? I can easily do

```
pipework_cmd=eth0 -i eth2 192.168.10.10/24@192.168.10.1
```

To add a single fixed macvlan interface to my container, but what if I want to add 2 or 3 interfaces, each with its own requirements?

The code _looks_ like it supports it based on the loop at https://github.com/dreamcat4/docker-images/blob/master/pipework/entrypoint.sh#L359 but how do I indicate that I want to run multiple commands?

**Comment by dreamcat4** [comment]
Hello @deitch !

Yes indeed that is correct, it's no problem. I apologise if the documentation which explains the feature is a little difficult to follow / understand.

If you go here:

https://github.com/dreamcat4/docker-images/blob/master/pipework/4.%20Config.md#pipework_cmd

It shows "Globbing Pattern" - and that is the regexp match for the env variable names it will recognise. Actually if you click the word "Globbing Pattern" there in blue hyperlink, it should take you to this paragraph, which further explain the purpose:

https://github.com/dreamcat4/docker-images/blob/master/pipework/4.%20Config.md#globbing

As you can see - any arbitrary prefix or suffix (or both). So you can put whatever id string before or after you wish. It will all be recognized. Please try for yourself, to check that the feature works to your satisfaction actually.

Many thanks.

**Comment by deitch** [comment]
Ah, now I see it. Yeah, definitely worth changing the README to show it. The overwhelming majority of containers have just one network port, but for those that have multiple, the globbing is invaluable.

Now I have to get dummy interfaces to work. pipework doesn't support it, but I put in a pull request for them to enable it. Once it does, I will open a new issue here to pull that in.

BTW, this is a great tool. I was planning on building something just like this, but you saved me tons of work.

**Comment by dreamcat4** [comment]
@deitch OK great.

Unfortunately one thing i notice yesterday is a lack of WAN connection with multiple interfaces. Not sure the reason. But my container with `eth0 + eth1` in it can only see my LAN addresses. So for example `ping -c1 8.8.8.8` inside the container does not work. Yet ping the local router `192.168.1.1` does work.

I just thought to mention it. Since you may also be affected too.

**Comment by deitch** [comment]
I don't understand. Can you tell me how to replicate it? I can spin up a digital ocean clean server and set up the containers and replicate it. If there is a problem, we can figure it out.

I know that I had a container with multiple eth yesterday that worked just fine.

**Comment by dreamcat4** [comment]
@deitch OK. I am glad to hear that news. Perhaps it is just a local issue then. In fact it used to work here too (wan on 2x interface) for me previously :ghost: 

I may try to make some simple example. Maybe that will help to narrow it down.

**Comment by dreamcat4** [comment]
Hello again @deitch. I have just uploaded an example code for how to reproduce a failed WAN connectivity (for multiple `pipework_cmd`s). You can see here exactly what I've been doing:

https://github.com/dreamcat4/docker-images/blob/master/wan.test/Dockerfile#L31-L56

If you have any ideas to try please let me know. Would be very grateful / appreciative.

**Comment by dreamcat4** [comment]
@deitch  OK nevermind about that. It seems to happen only when the `udhcpc` busybox container isn't exiting. Like this:

``` sh
docker ps
CONTAINER ID        IMAGE                         COMMAND                CREATED             STATUS              PORTS               NAMES
a7c2e871e781        busybox                       "udhcpc -i eth0 -x h   14 minutes ago      Up 14 minutes                           loving_poitras      
b9f967ec9e51        busybox                       "udhcpc -i eth0 -x h   39 minutes ago      Up 39 minutes                           cocky_hoover        
cfe45c2ea8cf        busybox                       "udhcpc -i eth1 -x h   About an hour ago   Up About an hour                        sad_curie           
ccd685ef3e72        busybox                       "udhcpc -i eth0 -x h   About an hour ago   Up About an hour                        stoic_payne         
840bd189b4ad        busybox                       "udhcpc -i eth0 -x h   About an hour ago   Up About an hour                        stoic_tesla         
a3abf57df7e7        dreamcat4/pipework            "/entrypoint.sh --he   46 hours ago        Up 9 minutes                            pipework            
cb3b16f03f0c        dreamcat4/tvheadend:testing   "/init /entrypoint.s   11 days ago         Up 8 hours                              tvh                 
id@emachines-e520:~/docker-images$ 
```

After stopping all of those errant containers, then it works again.

**Comment by deitch** [comment]
Glad you figured it out.
